apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: aksclusterconfigs.aks.cattle.io
spec:
  group: aks.cattle.io
  names:
    kind: AKSClusterConfig
    plural: aksclusterconfigs
    shortNames:
    - akscc
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            adminUsername:
              nullable: true
              type: string
            authBaseUrl:
              nullable: true
              type: string
            azureCredentialSecret:
              nullable: true
              type: string
            baseUrl:
              nullable: true
              type: string
            clusterName:
              nullable: true
              type: string
            displayName:
              nullable: true
              type: string
            dnsServiceIp:
              nullable: true
              type: string
            dockerBridgeCidr:
              nullable: true
              type: string
            imported:
              type: boolean
            kubernetesVersion:
              nullable: true
              type: string
            loadBalancerSku:
              nullable: true
              type: string
            masterDnsPrefix:
              nullable: true
              type: string
            networkPlugin:
              nullable: true
              type: string
            networkPolicy:
              nullable: true
              type: string
            nodePools:
              items:
                properties:
                  availabilityZones:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                  count:
                    type: integer
                  maxPods:
                    type: integer
                  mode:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                  orchestratorVersion:
                    nullable: true
                    type: string
                  osDiskSizeGB:
                    type: integer
                  osDiskType:
                    nullable: true
                    type: string
                  osType:
                    nullable: true
                    type: string
                  vmSize:
                    nullable: true
                    type: string
                type: object
              nullable: true
              type: array
            podCidr:
              nullable: true
              type: string
            privateAccess:
              type: boolean
            publicAccess:
              type: boolean
            publicAccessSources:
              items:
                nullable: true
                type: string
              nullable: true
              type: array
            resourceGroup:
              nullable: true
              type: string
            resourceLocation:
              nullable: true
              type: string
            serviceCidr:
              nullable: true
              type: string
            sshPublicKeyContents:
              nullable: true
              type: string
            subnet:
              nullable: true
              type: string
            subscriptionId:
              nullable: true
              type: string
            tags:
              additionalProperties:
                nullable: true
                type: string
              nullable: true
              type: object
            tenantId:
              nullable: true
              type: string
            virtualNetwork:
              nullable: true
              type: string
            virtualNetworkResourceGroup:
              nullable: true
              type: string
          type: object
        status:
          properties:
            failureMessage:
              nullable: true
              type: string
            phase:
              nullable: true
              type: string
            subnets:
              items:
                nullable: true
                type: string
              nullable: true
              type: array
            virtualNetwork:
              nullable: true
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
